server:
  port: 8080

app:
  kafka:
    bootstrap-servers: localhost:9092
    topic: log-topic
    consumer:
      group-id: log-group
      auto-offset-reset: earliest

  elasticsearch:
    baseUrl: http://localhost:9200
